- database/migrations/officina/2021_08_19_211521_create_officina_tables.up.sql
- database/migrations/patente/2021_08_19_211521_create_patente_tables.up.sql
Filter only people inside (popolazione.data_uscita IS NUL) in both the view `v_clienti_mecccanica" and `v_clienti_patente`
> show only people inside on view clienti meccanica and patenti

- src/App/Sin/Patente/Controllers/PatenteController.php
- src/App/Sin/Patente/Models/Patente.php
- add global scope to the patente model
> Show patenti of people that leave in  Nomadelfia

- src/App/Mail/PersonaEntrataMail.php
- src/App/Sin/Admin/Controllers/BackupController.php
- src/App/Sin/Admin/Models/User.php
- src/App/Sin/Biblioteca/Controllers/LibriController.php
- src/App/Sin/Biblioteca/Models/Libro.php
- src/App/Sin/Nomadelfia/Persona/Controllers/PersonaUscitaController.php
- src/App/Sin/Officina/Controllers/ApiController.php
- src/App/Sin/Officina/Models/Prenotazioni.php
- src/App/Sin/Officina/Models/Veicolo.php
- src/App/Sin/Officina/QueryBuilders/PrenotazioniQueryBuilders.php
- src/App/Sin/Patente/Controllers/PatenteController.php
- src/Domain/Nomadelfia/Persona/Models/Persona.php
- src/Domain/Nomadelfia/PopolazioneNomadelfia/Actions/LogEntrataPersonaAction.php
- src/Domain/Nomadelfia/PopolazioneNomadelfia/Actions/SendEmailPersonaEntrataAction.php
- src/Domain/Nomadelfia/PopolazioneNomadelfia/Actions/UscitaPersonaAction.php
- src/Domain/Nomadelfia/PopolazioneNomadelfia/Actions/UscitaPersonaDBAction.php
- src/Domain/Nomadelfia/PopolazioneNomadelfia/Models/Cariche.php
- tests/Biblioteca/Feature/BooksPageTest.php
- tests/Pest.php
- tests/Popolazione/Unit/PopolazioneTest.php
If a son exit the community, he/she is also deactivated from the family.
> Fix: deactivate the son from the family when he exit from the community

- composer.json
- composer.lock
- database/factories/PhotoFactory.php
- database/migrations/foto/2023_07_07_100131_create_photos_table.up.sql
- database/seeders/LocalEnvironmentSeeder.php
- database/seeders/PhotoTableSeeder.php
- src/App/Console/Commands/ExifExtractCommand.php
- src/App/Console/Commands/ExifJsonImportCommand.php
- src/App/Console/Kernel.php
- src/Domain/Photo/Actions/ExtractExifAction.php
- src/Domain/Photo/Actions/StoreExifIntoDBAction.php
- src/Domain/Photo/Exif/ExifReader.php
- src/Domain/Photo/Models/ExifData.php
- src/Domain/Photo/Models/Photo.php
- tests/Photo/Command/ExifExtractCommandTest.php
- tests/Photo/Exif/ExifReaderTest.php
Add the following command:
- `exif:extract  PATH`: run the exif tool command to save metadata into a json file
- `exif:import  file` to import the json obtained by exiftool
TODO
-  move photos and put into a directory structure divided year and month  `exiftool -d %Y/%m "-directory<filemodifydate" "-directory<createdate" "-directory<datetimeoriginal" /media/dido/LUMIX/DCIM/110_PANA .`
> Refactor exif command

- phpstan-baseline.neon
- resources/views/admin/auth/roles/create.blade.php
- src/App/Sin/Admin/Controllers/RisorsaController.php
- src/App/Sin/Admin/Controllers/RoleController.php
The Role controller was broker because it used the deleted `Sistema` models.
Fix  by using the permissions,
> Fix role controller

- resources/views/biblioteca/libri/etichette/view.blade.php
A removed route cause issue in a commented html view.
> fix view etichette

- Taskfile.yml
- resources/views/livewire/search-persona.blade.php
- resources/views/nomadelfia/popolazione/show.blade.php
- resources/views/officina/prenotazioni/index.blade.php
- src/App/Livewire/SearchPersona.php
Added a `<livewire:search-persona>` component to search the clients.
> feat: add livewire component to search people

- phpunit.xml
- resources/views/livewire/search-persona.blade.php
- src/App/Livewire/SearchPersona.php
- tests/Livewire/SearchPersonaTest.php
- tests/Pest.php
the search starts on every character typed.
- start searching if at least 2 chars are inserted
- add message of no items into the component 
- add tests
> feat: search-persona search after the second char is inserted

- resources/views/livewire/prenotazione-veicoli.blade.php
- resources/views/officina/prenotazioni/index.blade.php
The current request-response latency is around `1.70` seconds.
The livewire componenent
> feat(officina): enable prenotazione-veicoli livewire on `index` page

- composer.lock
```
- Upgrading php-http/discovery (1.19.2 => 1.19.4): Extracting archive
- Upgrading symfony/polyfill-mbstring (v1.28.0 => v1.29.0): Extracting archive
- Upgrading symfony/var-dumper (v6.4.0 => v6.4.6): Extracting archive
- Upgrading maximebf/debugbar (v1.19.1 => v1.22.3): Extracting archive
- Upgrading symfony/polyfill-php80 (v1.28.0 => v1.29.0): Extracting archive
- Upgrading symfony/polyfill-ctype (v1.28.0 => v1.29.0): Extracting archive
- Upgrading symfony/css-selector (v6.4.0 => v6.4.3): Extracting archive
- Upgrading symfony/polyfill-uuid (v1.28.0 => v1.29.0): Extracting archive
- Upgrading symfony/uid (v6.4.0 => v6.4.3): Extracting archive
- Upgrading symfony/routing (v6.4.1 => v6.4.6): Extracting archive
- Upgrading symfony/process (v6.4.0 => v6.4.4): Extracting archive
- …
```
> chore: upgrade composer deps

- resources/views/rtn/video/create.blade.php
Slightly change the view of the insert of a new archivio professionale
> refact(archivioprofessionale): view to add a new  video of the archivio professionale

- resources/views/scuola/elaborati/edit.blade.php
- resources/views/scuola/elaborati/show.blade.php
- routes/web.php
- src/App/Sin/Scuola/Controllers/ElaboratiController.php
- src/App/Sin/Scuola/DataTransferObjects/AnnoScolastico.php
Add edit button for: annoscolastico, titile, note
> feat(elaborati): add edit of base info

- resources/views/scuola/elaborati/edit.blade.php
- resources/views/scuola/elaborati/show.blade.php
- src/App/Livewire/SearchPersona.php
- src/App/Sin/Scuola/Controllers/ElaboratiController.php
Edit the studenti and classi of elaborato.
> feat(elaborati): edit studenti and classi

- Taskfile.yml
- database/migrations/common/2023_10_24_221648_add_scuola_reference_to_persone.up.sql
- database/migrations/db_nomadelfia/2022_12_04_004646_create_view_popolazione_attuale.up.sql
- database/migrations/scuola/2021_11_04_221053_create_elaborati_table.up.sql
- database/migrations/scuola/2024_08_13_114421_add_elaborati_coordinatori.down.sql
- database/migrations/scuola/2024_08_13_114421_add_elaborati_coordinatori.php
- database/migrations/scuola/2024_08_13_114421_add_elaborati_coordinatori.up.sql
- docker-compose.yml
- resources/views/livewire/search-persona.blade.php
- resources/views/scuola/elaborati/create.blade.php
- resources/views/scuola/elaborati/edit.blade.php
- resources/views/scuola/elaborati/show.blade.php
- src/App/Livewire/SearchPersona.php
- src/App/Sin/Scuola/Controllers/ElaboratiController.php
- src/App/Sin/Scuola/Models/Elaborato.php
- tests/MigrateFreshDB.php
- add coordinatori 
- add `inputName` in the `SearchPersona`
> feat(elaborati) add coordinatori + `searchPersona` with inputName

- database/factories/ElaboratoFactory.php
- src/App/Sin/Scuola/Controllers/ElaboratiController.php
- src/App/Sin/Scuola/DataTransferObjects/AnnoScolastico.php
- src/App/Sin/Scuola/DataTransferObjects/Dimensione.php
- src/App/Sin/Scuola/Models/Elaborato.php
- tests/Scuola/Http/ElaboratiTest.php
If the dimensione was null, the update function failed.
> fix(elaborati): update elaborato with null dimensione

- resources/views/scuola/templates/aggiungiAlunno.blade.php
- src/App/Sin/Scuola/Models/Classe.php
- src/Domain/Nomadelfia/PopolazioneNomadelfia/Models/PopolazioneNomadelfia.php
- tests/Scuola/Unit/ScuolaTest.php
In the `add student` button, the same person was shown multiple times.
Remove the join with the `popolazione` table. No need to use that table.
> fix(scuola): the same persons was shown multiple times

- phpstan-baseline.neon
- resources/views/scuola/templates/aggiungiAlunno.blade.php
- src/App/Sin/Scuola/Models/Classe.php
- change order by to show men vs women to respect the printed version
- expand the select option to the number of available kids
> chore(scuola): scuola index order alunni by Sesso, nominativo

- phpstan-baseline.neon
- resources/views/patente/search.blade.php
- routes/api.php
- src/App/Sin/Patente/Controllers/ApiController.php
- src/App/Sin/Patente/Models/ViewClientiConSenzaPatente.php
the autocomplete was not working.
Use the `livewire:search-persona` component
> fix(patente): use livewire compoment to search patente via persona

- composer.json
- composer.lock
```
- Upgrading symfony/finder (v6.4.11 => v6.4.13): Extracting archive
- Upgrading symfony/deprecation-contracts (v3.5.0 => v3.5.1): Extracting archive
- Upgrading symfony/var-dumper (v6.4.11 => v6.4.15): Extracting archive
- Upgrading maximebf/debugbar (v1.22.5 => v1.23.3): Extracting archive
- Upgrading voku/portable-ascii (2.0.1 => 2.0.3): Extracting archive
- Upgrading symfony/css-selector (v6.4.8 => v6.4.13): Extracting archive
- Upgrading symfony/uid (v6.4.11 => v6.4.13): Extracting archive
- Upgrading symfony/routing (v6.4.11 => v6.4.16): Extracting archive
- Upgrading symfony/process (v6.4.8 => v6.4.15): Extracting archive
- Upgrading symfony/mime (v6.4.11 => v6.4.13): Extracting archive
- Upgrading symfony/service-contracts (v3.5.0 => v3.5.1): Extracting archive
- Upgrading …
```
> chore: update deps + remove `laracasts/utilities`

- resources/views/nomadelfia/templates/eliminaIncarico.blade.php
- resources/views/officina/prenotazioni/search_form.blade.php
- src/App/Providers/AppServiceProvider.php
- src/App/Sin/Officina/Models/ViewMeccanici.php
Add 
1. Model::preventSilentlyDiscardingAttributes();
2. Model::preventAccessingMissingAttributes();
3. Model::unguard();
TODO:
- the 1. and 2.   are included into the `Model::shouldBeStrict()`. Avoid (for now) because the disableLazyloading generates more errors.
- Enable the `Model::shouldBeStrict();`
> refact: add model guard in app service provider

- database/seeders/OfficinaMeccanicaTableSeeder.php
- resources/views/officina/prenotazioni/search_form.blade.php
> fix(meccanica): fix access not existing prop on viewclienti model

- resources/views/nomadelfia/famiglie/show.blade.php
- resources/views/nomadelfia/templates/aggiornaFamiglia.blade.php
> fix(nomadelfia) update family name variable references in views

- src/App/Sin/Scuola/Models/Classe.php
Chnage the alunni possibili:
- prescuola: from 2 to 7 years
- elementari: from 5 to 25 years
> fix: adjust year calculations for class date ranges

- src/App/Sin/Scuola/Models/Classe.php
- elementari:  5 - 13 
- medie: 10- 20 (per coprire i casi delle persone che stavano in terza media per sempre)
> fix: update date range calculations for different school types 

- database/migrations/scuola/2021_08_19_211521_create_scuola_table.up.sql
- phpstan-baseline.neon
- resources/views/scuola/classi/show.blade.php
- resources/views/scuola/templates/modificaTipoClasse.blade.php
- routes/web.php
- src/App/Sin/Scuola/Controllers/ClassiTipoController.php
- tests/Scuola/Http/ClasseTest.php
- tests/Scuola/Http/ScuolaTest.php
- edit the tipo of a classe 
- removed the ` CONSTRAINT unique_classe_as UNIQUE (tipo_id, anno_id)` constraint. In the same year the same class can be duplicated
> feat(scuola): edit classe type

- phpstan-baseline.neon
- resources/views/scuola/anno/show.blade.php
- resources/views/scuola/anno/storico.blade.php
- resources/views/scuola/summary.blade.php
- src/App/Sin/Scuola/Controllers/ScuolaController.php
- src/App/Sin/Scuola/QueryBuilders/StudenteQueryBuilder.php
- tests/Scuola/Unit/ScuolaTest.php
Add alunni count on year and single school year
> feat(scuola): add alunni count to views

- phpstan-baseline.neon
- resources/views/scuola/anno/show.blade.php
- resources/views/scuola/anno/storico.blade.php
- resources/views/scuola/templates/aggiungiNoteAnno.blade.php
- routes/web.php
- src/App/Sin/Scuola/Controllers/AnnoScolasticoClassiController.php
- src/App/Sin/Scuola/Controllers/AnnoScolasticoController.php
- src/App/Sin/Scuola/Controllers/AnnoScolasticoNoteController.php
- src/App/Sin/Scuola/Controllers/ClassiController.php
- src/App/Sin/Scuola/Controllers/ScuolaController.php
- tests/Scuola/Http/ClasseTest.php
- tests/Scuola/Http/ScuolaTest.php
Add the description on the show of the anno scolastico
> feat(scuola): aggiorna nota anno scolastico

- resources/views/scuola/anno/show-new.blade.php
- resources/views/scuola/anno/storico.blade.php
- resources/views/scuola/templates/cloneAnnoDaPrecedente.blade.php
- src/App/Sin/Scuola/Controllers/AnnoScolasticoNoteController.php
- src/App/Sin/Scuola/DataTransferObjects/AnnoScolasticoData.php
- update the note with empty string is now possible.
> fix(scuola): edit the show of a single year and order by tipo and alunno

- phpstan-baseline.neon
- resources/views/scuola/templates/aggiungiClasse.blade.php
- src/App/Sin/Scuola/Models/Anno.php
- tests/Scuola/Unit/ScuolaTest.php
Allow to create the same classe in the same anno.
> feat(scuola): allow same classe in anno

- database/migrations/scuola/2021_08_19_211521_create_scuola_table.up.sql
- package-lock.json
- phpstan-baseline.neon
- resources/views/biblioteca/libri/book.blade.php
- resources/views/scuola/classi/show.blade.php
- resources/views/scuola/templates/aggiungiNoteClasse.blade.php
- routes/web.php
- src/App/Sin/Scuola/Controllers/ClassiNoteController.php
- change `anno.descrizione` type  from varchar to TEXT to be able to add longer description
- add a column `note` on the classi table
> feat(scuola) add note on classe

- package-lock.json
- package.json
- resources/js/app.js
> chore: remove moment.js dependency from package.json and app.js

- resources/js/app.js
- revert function that avoid sending input with null
> feat(app.js): disable empty input fields on form submission

- package-lock.json
- package.json
- resources/js/app.js
- resources/js/bootstrap.js
- renable jquery beacuse there is a script that avoid sending null value when a post is sent
- This error appears: fix both the vue and vue-template-compiler to the same version
```
Vue packages version mismatch:
- vue@2.6.14 (C:\xampp\htdocs\sin\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.7.16 (C:\xampp\htdocs\sin\node_modules\vue-template-compiler\package.json)
```
> fix: install jquery + vue-template-compiler version mismatch:

- package-lock.json
- package.json
- resources/js/app.js
- resources/js/bootstrap.js
- resources/views/layouts/app.blade.php
- routes/api.php
- webpack.mix.js
> :1st_place_medal:  remove `vue`  :1st_place_medal: 

- resources/views/scuola/elaborati/show.blade.php
- resources/views/scuola/student/show.blade.php
- resources/views/scuola/templates/student.blade.php
- routes/web.php
- src/App/Sin/Scuola/Controllers/StudentController.php
- src/App/Sin/Scuola/Models/Studente.php
Add a simple page with 
- personal info
- list of classi
- list of elaborati
> feat(scuola): add first student page

- phpstan-baseline.neon
- resources/views/scuola/student/show.blade.php
- src/App/Sin/Scuola/Controllers/StudentController.php
- tests/Scuola/Http/StudentTest.php
Order by year the classes and works of the studetns
> chore(scuola): improve student show page

- resources/views/nomadelfia/persone/show.blade.php
- add the link to the `student` page into the person page
- only user with the permission `scuola.visualizza` can see the link
> chore(popolazione): add student ref 

- resources/views/scuola/elaborati/index.blade.php
- resources/views/scuola/elaborati/show.blade.php
- src/App/Sin/Scuola/Controllers/ElaboratiController.php
- add gray background if cover is missing
> feat(elaborati): better elaborati index 

- src/App/View/Components/MyModal.php
fix the MyModal class to psr-4 autoloading standard.
> fix: myModal class naming 

- resources/views/scuola/elaborati/create.blade.php
- resources/views/scuola/elaborati/edit.blade.php
- resources/views/scuola/elaborati/show.blade.php
- src/App/Sin/Scuola/DataTransferObjects/Dimensione.php
- tests/Biblioteca/Http/BooksPageTest.php
- tests/Scuola/Unit/ElaboratoTest.php
Enhanche the dimension handling.
Changes
- define in millimeter (TODO: execute migration on db) + `a3` or `a4`
- add uni test
> feat(dimension): enhance dimension handling and validation

- routes/web.php
> fix(patente): allow unauthenticated access to the preview route for pdf export

- resources/views/home.blade.php
there is a mispelled button text + removed the duplicated `archivio libri`
> fix(home): update button text and remove duplicated card section

- phpstan-baseline.neon
- phpunit.xml
- resources/views/agraria/home.blade.php
- resources/views/agraria/index.blade.php
- resources/views/agraria/maintenanance/create.blade.php
- resources/views/agraria/maintenanance/search.blade.php
- resources/views/agraria/mezzi/create.blade.php
- resources/views/agraria/mezzi/edit.blade.php
- resources/views/agraria/mezzi/hour/create.blade.php
- resources/views/agraria/mezzi/index.blade.php
- resources/views/agraria/mezzi/show.blade.php
- resources/views/layouts/app.blade.php
- resources/views/livewire/filter-alunno.blade.php
- resources/views/nomadelfia/persone/effettivi.blade.php
- resources/views/partials/errors.blade.php
- routes/web.php
- src/App/Sin/Agraria/Controllers/AgrariaController.php
- src/App/Sin/Agraria/Controllers/MaintenanceController.php
- src/App/Sin/Agraria/Controllers/MezziController.php
- src/App/Sin/Agraria/Controllers/SearchableMaintenanceController.php
- src/App/Sin/Agraria/Models/Manutenzione.php
- src/App/Sin/Agraria/Models/MezzoAgricolo.php
- tests/Agraria/Http/AgrariaTest.php
- tests/Agraria/Http/MaintenancesTest.php
- tests/MigrateFreshDB.php
- tests/Pest.php
> refactor(agraria): improve layout, naming, controllers

- phpstan-baseline.neon
- src/App/Sin/Scuola/Controllers/ClassiController.php
- src/App/Sin/Scuola/Models/Classe.php
- src/App/Sin/Scuola/Models/ClasseTipo.php
If data_inizio is not present se the data of the year
> fix(classi): Refactor data_inizio handling to use class year default year

- resources/views/nomadelfia/cariche/edit.blade.php
- resources/views/nomadelfia/gruppifamiliari/edit.blade.php
- resources/views/scuola/classi/show.blade.php
- src/App/Providers/BladeDirectivesServiceProvider.php
- src/App/Sin/Scuola/Models/Classe.php
…d adjust ordering in Classe model
> fix(scuola): Update Blade directives to use diffHumans for age calculation 

- app/Http/Nomadelfia/PopolazioneNomadelfia/Controllers/PrintableExcelPopolazioneController.php
- app/Http/Nomadelfia/PopolazioneNomadelfia/Controllers/PrintableWordPopolazioneController.php
- phpstan-baseline.neon
- routes/web.php
- tests/Popolazione/Http/PopolazioneTest.php
- Add the NOMINATIVO column into the exported excel
- Convert the string with `Str::title()` to have the first letter of each word capitalized.
NOTE:
The name and surname should be capitalized in the DB (and not in the code). For speed reason I used the Str method
> feat(nomadelfia): add nominativo to export excel

- app/Http/Photo/Controllers/FavouritesController.php
- app/Http/Photo/Controllers/PhotoController.php
- resources/views/photo/favorite/index.blade.php
- resources/views/photo/index.blade.php
- resources/views/photo/main.blade.php
- resources/views/photo/show.blade.php
- routes/web.php
- add navigation with photo and favorites
- use figure instead of card + img
> feat(photo): add navigation menu + use figure

- app/Http/Photo/Actions/StoreExifIntoDBAction.php
- app/Http/Photo/Controllers/FavouritesController.php
- app/Http/Photo/Controllers/PhotoController.php
- app/Http/Photo/Models/ExifData.php
- app/Http/Photo/Models/Photo.php
- database/factories/PhotoFactory.php
- database/migrations/foto/2025_05_16_180350_alter_photos_uid.down.sql
- database/migrations/foto/2025_05_16_180350_alter_photos_uid.php
- database/migrations/foto/2025_05_16_180350_alter_photos_uid.up.sql
- resources/views/photo/favorite/index.blade.php
- resources/views/photo/index.blade.php
- resources/views/photo/show.blade.php
- routes/web.php
- tests/Photo/Http/PhotoControllerTest.php
Change the uid (from a string) to a int (autocincrement)
> feat(photo): change the uid to id 

- database/migrations/db_nomadelfia/2025_05_21_090956_add_persona_indexes.down.sql
- database/migrations/db_nomadelfia/2025_05_21_090956_add_persona_indexes.php
- database/migrations/db_nomadelfia/2025_05_21_090956_add_persona_indexes.up.sql
- database/migrations/foto/2025_05_21_090812_add_photo_indexes.down.sql
- database/migrations/foto/2025_05_21_090812_add_photo_indexes.php
- database/migrations/foto/2025_05_21_090812_add_photo_indexes.up.sql
The query to get the faces took 2.5seconds
> feat(photo): add indexes to speed up faces

- app/Http/Photo/Controllers/FaceController.php
- resources/views/photo/face/index.blade.php
The like with '%' operator does not use the index.
> fix(photo): remove % from the query to get faces to use the index

- app/Http/Photo/Controllers/FaceController.php
- app/Http/Photo/Controllers/FavouritesController.php
- app/Http/Photo/Controllers/LegendController.php
- resources/views/photo/favorite/index.blade.php
- resources/views/photo/slideshow/index.blade.php
- routes/web.php
> feat(photo): add LegendController for exporting legend in word

- composer.json
- composer.lock
Upgrade to laravel 12
```
- Upgrading symfony/finder (v7.2.2 => v7.3.0): Extracting archive
- Upgrading symfony/polyfill-mbstring (v1.31.0 => v1.32.0): Extracting archive
- Upgrading symfony/deprecation-contracts (v3.5.1 => v3.6.0): Extracting archive
- Upgrading symfony/var-dumper (v7.2.3 => v7.3.0): Extracting archive
- Upgrading symfony/polyfill-php80 (v1.31.0 => v1.32.0): Extracting archive
- Upgrading symfony/polyfill-ctype (v1.31.0 => v1.32.0): Extracting archive
- Upgrading vlucas/phpdotenv (v5.6.1 => v5.6.2): Extracting archive
- Upgrading symfony/css-selector (v7.2.0 => v7.3.0): Extracting archive
- Upgrading symfony/polyfill-uuid (v1.31.0 => v1.32.0): Extracting archive
- Upgrading symfony/uid (v7.2.0 => v7.3.0): Extracting archive
- Upgrading symfony/routing (v7.2.3 => v7.3.0): …
```
> chore: upgrade to laravel 12

- composer.json
- composer.lock
Add the https://nightwatch.laravel.com/  to the project.
TODO: compare the metrics with the sentry ones.
> feat: add `laravel/nightwatch`  

- app/Providers/AppServiceProvider.php
- phpstan-baseline.neon
Tag the event with the reals username of the user.
Before only the ID was shown.
> feat(Nightwatch): edit the service provider to send  username

- app/Http/Agraria/Controllers/MaintenanceController.php
- app/Http/Nomadelfia/EserciziSpirituali/Controllers/EsSpiritualiController.php
- app/Http/Nomadelfia/EserciziSpirituali/Models/EserciziSpirituali.php
- app/Http/Nomadelfia/Famiglia/Models/Famiglia.php
- app/Http/Nomadelfia/GruppoFamiliare/Models/GruppoFamiliare.php
- app/Http/Nomadelfia/Persona/Models/Persona.php
- app/Http/Nomadelfia/PopolazioneNomadelfia/Models/Cariche.php
- app/Http/Nomadelfia/PopolazioneNomadelfia/Models/PopolazioneNomadelfia.php
- app/Http/Nomadelfia/PopolazioneNomadelfia/Models/Posizione.php
- app/Http/Nomadelfia/PopolazioneNomadelfia/Models/Stato.php
- app/Http/Officina/Models/Modelli.php
- app/Http/Officina/Models/Prenotazioni.php
- app/Http/Officina/Models/TipoFiltro.php
- app/Http/Officina/Models/TipoGomme.php
- app/Http/Officina/Models/Veicolo.php
- app/Http/Patente/Controllers/PatenteElenchiController.php
- app/Http/Patente/Controllers/PatenteSearchController.php
- app/Http/Patente/Models/ViewClientiConSenzaPatente.php
- app/Http/Rtn/Video/Video.php
- app/Http/Scuola/Models/Classe.php
- app/Http/Scuola/Models/ClasseBuilder.php
- phpstan-baseline.neon
- resources/views/agraria/maintenanance/show.blade.php
- routes/web.php
add button to delete + removed comments
> feat(agraria): Delete manutenzione

- app/Livewire/SearchPersona.php
from 20 to 50 because to show more results
> feat(livewire) increase limit sercah persona
